services:
  - type: web
    name: painel-indicadores
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: "SUA_STRING_DE_CONEXÃO_DO_SQL_SERVER"
